#!/bin/bash

# ─────────────────────────────────────────────────────────────
# GASAK ENGINE TOOLCHAIN - ULTIMATE COMPREHENSIVE INSTALLER
# Target OS: Debian, Ubuntu, Linux Mint, dan turunannya.
# (100% FIXED FOR GO-PYTHON RUNTIME COMPATIBILITY)
# ─────────────────────────────────────────────────────────────

set -euo pipefail

# ─── CONFIGURATION ───────────────────────────────────────────
SERVER_IP="10.70.0.110"
SERVER_PORT="9001"
BASE_URL="http://${SERVER_IP}:${SERVER_PORT}"
INSTALL_DIR="$HOME/gasak-dist"

# ANSI Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
PURPLE='\033[0;35m'
RESET='\033[0m'

clear
echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
echo -e "${CYAN}  GASAK ENGINE TOOLCHAIN - AUTOMATIC COMPLETE INSTALLER     ${RESET}"
echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"

# ─── HELPER FUNCTIONS ─────────────────────────────────────────
ok()   { echo -e "   ${GREEN}[✔] $1${RESET}"; }
err()  { echo -e "   ${RED}[✘] $1${RESET}"; }
info() { echo -e "   ${CYAN}[->] $1${RESET}"; }
warn() { echo -e "   ${YELLOW}[!] $1${RESET}"; }

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# ─── STEP 1: DETEKSI RUNTIME PYTHON & PIP ────────────────────
info "Mendeteksi ketersediaan Python & PIP lokal..."
PYTHON_CMD="python3"
PIP_CMD="pip3"

if ! command_exists python3; then
    warn "Python3 tidak terdeteksi secara global. Akan dipasang via APT."
fi

# ─── STEP 2: INSTALL DEPENDENSI SISTEM VIA APT ───────────────
info "Sinkronisasi repositori & pasang dependensi core sistem..."
echo -e "   ${PURPLE}(Membutuhkan hak akses sudo untuk melengkapi library sistem)${RESET}"

sudo -v
# --- TAMBAHKAN BARIS AUTO-REPAIR INI ---
info "Melakukan auto-repair pada apt package manager (jika ada broken)..."
sudo dpkg --configure -a || true
sudo apt-get install -f -y || true
# ---------------------------------------

sudo apt-get update -y

# Dependensi mutlak: python3-tk (untuk log_cleaner UI), fzf (untuk iterfzf di deploy tool)
APT_DEPS=(
    "sshpass" "rsync" "unzip" "fzf" "curl" "iputils-ping"
    "python3" "python3-pip" "python3-tk"
)

for pkg in "${APT_DEPS[@]}"; do
    if dpkg -s "$pkg" >/dev/null 2>&1; then
        ok "Paket sistem '${pkg}' sudah siap."
    else
        info "Menginstall paket '${pkg}'..."
        sudo apt-get install -y "$pkg"
    fi
done

# ─── STEP 3: INISIALISASI FOLDER DISTRIBUSI ───────────────────
info "Menyiapkan sandbox folder instalasi di ${INSTALL_DIR}..."
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR" || exit 1

# ─── STEP 4: DOWNLOAD KOMPONEN DARI SERVER DISTRIBUSI ────────
info "Mengunduh seluruh toolchain component dari server pusat..."

FILES_TO_DOWNLOAD=(
    "gasak"
    "decode_and_merge.py"
    "deploy_parkee.py"
    "log_cleaner.py"
    "settlement_rfs.py"
    "version.txt"
    "server.properties"
)

DOWNLOAD_FAILED=()

for file in "${FILES_TO_DOWNLOAD[@]}"; do
    echo -n -e "   -> Mengunduh ${file}... "
    if curl -fsSL "${BASE_URL}/${file}" -o "${INSTALL_DIR}/${file}"; then
        echo -e "${GREEN}BERHASIL${RESET}"
    else
        echo -e "${RED}GAGAL${RESET}"
        DOWNLOAD_FAILED+=("$file")
    fi
done

if [ ${#DOWNLOAD_FAILED[@]} -ne 0 ]; then
    err "Beberapa file krusial gagal diunduh: ${DOWNLOAD_FAILED[*]}"
    err "Pastikan server distribusi di ${SERVER_IP}:${SERVER_PORT} nyala men!"
    exit 1
fi

# ─── STEP 5: AUTO-GENERATE .env (HARDCODED CREDENTIALS) ──────
info "Menyuntikkan konfigurasi .env internal tim..."

ENV_PATH="${INSTALL_DIR}/.env"

cat << 'EOF' > "$ENV_PATH"
# ─────────────────────────────────────────────────────────────
# GASAK CONFIGURATION - AUTO-GENERATED BY INSTALLER
# (HARDCODED CREDENTIALS FOR INTERNAL USE ONLY)
# ─────────────────────────────────────────────────────────────

# URLs
GLPI_URL=https://parkee-ticket.nusa.technology/
OUTLINE_URL=https://docs.sistemparkiran.com/home

# API Keys
OUTLINE_API_KEY=REMOVED_OUTLINE_KEY
LINEAR_API_KEY=REMOVED_LINEAR_KEY

# SSH Credentials
PARKEE_SSH_USER=support
PARKEE_SSH_PASS=REMOVED_PASSWORD

# CMS Database
CMS_DB_HOST=newdbparkeeproduction.cmxwbzwcs2rw.ap-southeast-1.rds.amazonaws.com
CMS_DB_PORT=5432
CMS_DB_USER=product
CMS_DB_PASS=Parkee545115
CMS_DB_NAME=parkee
EOF

chmod 600 "$ENV_PATH"
ok "File .env berhasil dibuat dan dikunci di ${ENV_PATH}."

# ─── STEP 6: INSTALASI PIP DEPENDENCIES (ANTI VENV TRAP) ──────
info "Menginstal modul Python lokal pengguna (Global-Accessible)..."

# Semua paket python yang di-import di settlement_rfs, deploy_parkee, dan log_cleaner
PIP_PACKAGES=("psycopg2-binary" "requests" "questionary" "iterfzf" "rich")

# Solusi Jitu: Menggunakan --user dan --break-system-packages supaya
# package langsung masuk ke scope python3 global user tanpa terisolasi venv.
# Jadi saat binary Go manggil 'python3', paket-paket ini langsung terbaca!
if $PIP_CMD install --user --break-system-packages "${PIP_PACKAGES[@]}" > /dev/null 2>&1; then
    ok "Seluruh modul python sukses dikonfigurasikan di sistem lokal."
else
    warn "Gagal eksekusi standar pip user bypass. Mencoba metode alternatif..."
    $PIP_CMD install --break-system-packages "${PIP_PACKAGES[@]}" > /dev/null 2>&1 || {
        err "Gagal mengkonfigurasi modul python. Cek izin pip lu men."
        exit 1
    }
    ok "Modul python berhasil dikonfigurasikan."
fi

# ─── STEP 7: FIX PERMISSIONS (MUTLAK) ─────────────────────────
info "Mengunci izin akses berkas toolchain..."
chmod +x "${INSTALL_DIR}/gasak"

# Script python dipanggil lewat 'python3 script.py' oleh Go, jadi cukup read-only aman (644)
chmod 644 "${INSTALL_DIR}/"*.py 2>/dev/null || true
chmod 644 "${INSTALL_DIR}/version.txt" 2>/dev/null || true
chmod 644 "${INSTALL_DIR}/server.properties" 2>/dev/null || true
ok "Seluruh hak akses berkas diatur dengan aman."

# ─── STEP 8: REGISTRASI PROFILE SHELL ALIAS ───────────────────
info "Mendaftarkan alias perintah 'gasak' ke profil terminal..."

ALIAS_STR="alias gasak='${INSTALL_DIR}/gasak'"
SHELL_PROFILES=("$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile")

for profile in "${SHELL_PROFILES[@]}"; do
    if [ -f "$profile" ]; then
        if ! grep -q "alias gasak=" "$profile"; then
            echo "" >> "$profile"
            echo "# GASAK Toolchain Automation Engine Alias" >> "$profile"
            echo "$ALIAS_STR" >> "$profile"
            info "Alias sukses terdaftar di ${profile}"
        fi
    fi
done

# ─── FINAL SUMMARY RINGKASAN INSTALASI ─────────────────────────
echo ""
echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
echo -e "${GREEN}  ✔ GASAK TOOLCHAIN SUKSES TERPASANG TOTAL DI LAPTOP LU MEN!   ${RESET}"
echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
echo -e "  • Lokasi Install  : ${CYAN}${INSTALL_DIR}${RESET}"
echo -e "  • Status .env     : ${GREEN}TERSEDIA & INTEGRATED (Hardcoded)${RESET}"
echo -e "  • UI Toolkit (Tk) : ${GREEN}READY (python3-tk Terpasang)${RESET}"
echo -e "  • FZF Extension   : ${GREEN}READY (fzf Core Terpasang)${RESET}"
echo -e "  • SSH Automation  : ${GREEN}READY (sshpass Terpasang)${RESET}"
echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${YELLOW}BIAR COMMAND LANGSUNG AKTIF TANPA RESTART TERMINAL, KETIK DOANG:${RESET}"
echo -e "  ${CYAN}source ~/.bashrc${RESET}   atau   ${CYAN}source ~/.zshrc${RESET}"
echo ""
echo -e "  Sekarang tim lu tinggal ngetik: ${GREEN}gasak${RESET} di mana aja, aman aman bae bre!"
echo ""
