serverHost=10.70.0.16
dbHost=10.70.0.16
dbPort=5432
db=agent_00f
connectionTimeout=20000
wsHost=10.70.0.16
wsPort=9005
kafkaHost=10.70.0.16
kafkaPort=9092
cache.client.impl=redis
redisHost=10.70.0.16
redisPort=6379
redisTimeout=2000
redisConnectTimeout=20000
redisOperationTimeout=20000
redisMaxConnection=25000
redisIdleConnection=
ftp.host=36.66.126.17
ftp.username=parkee
ftp.password=parkee545115
ftp.dir=/home/parkee/Desktop/parkee/settlement/Request
local.dir=/Users/parkee/Downloads
minio.endpoint=http://10.70.0.16:9000
minio.accesskey=minioadmin
minio.secretkey=minioadmin
leakDetectionThreshold=12000
maximumPoolSize=3
minio.writeTimeout=20000
minio.readTimeout=20000
minio.connectTimeout=20000
fisherman.host=10.70.0.16
fisherman.port=8888
qiqo.password=bsv1t3HqsCySrtsEj-rX
qiqo.salt=cWzFTWf9HSleQ9zPgCTL
membership.card.mode=parkee
membership.card.mode.support.custom=parkee
normalize.membership.mode=off
redis.pubsub.mode=on
redis.mode=on
redis.lpr=true
redis.retry=30
environment=staging
redis.sync.mode=true
lpr.receiver=redis
parkee.payment.mode=kafka
maintenance.mode=false
credential.information=0HNGn43b+kafk7i79cXoODpyZT4VFXObHJOidohSdDo=--A4haCqq9RPkz80JyNl6H5A==
